name: NerdyConnections
favicon: null
layout_spectrum: 0.2711961711756885
typography_spectrum: 0.648484023520723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8105204347521067
  lightness: 0.7462094859220088
  saturation: 0.5488462373614311
  rhythmicContrast: 0.22322030877694488
purpose: []
